### ISSUE TITLE
Dropping `all` in comma separated media query

### ISSUE THREAD

**Issue by marszall87** [ben-eb/postcss-minify-params#5]
For this input:
```css
@media all, (max-device-width: 0) {
    h1 {
        color: red;
    }
}
```

I receive this output:
```css
@media ,(max-device-width: 0) {
    h1 {
        color: red;
    }
}
```

Apparently browsers treat that query as `@media not all, (max-device-width: 0)` and obviously it's not what you expect.

You can see in this JS Bin that the second rule is ignored:
[https://jsbin.com/mipozuh/edit?html,css,output](https://jsbin.com/mipozuh/edit?html,css,output)

The first rule is actually translated by Chrome to `@media not all, (max-device-width: 999999px)`:
![image](https://user-images.githubusercontent.com/4551693/32607245-8ec76042-c558-11e7-9f61-ec3b1e7ba3c0.png)

I'm using version `1.2.2`.
